import 'dotenv/config';
import { z } from 'zod';

const boolFromEnv = z
  .string()
  .optional()
  .transform((value) => ['1', 'true', 'yes', 'on'].includes(String(value ?? '').toLowerCase()));

const envSchema = z.object({
  NODE_ENV: z.string().default('development'),
  HOST: z.string().default('127.0.0.1'),
  PORT: z.coerce.number().default(8787),
  WEB_ORIGIN: z.string().default('http://127.0.0.1:5173'),
  AUTONOMY_ENABLED: boolFromEnv,
  AUTONOMY_CRON: z.string().default('*/30 * * * *'),
  AUTONOMY_TOP_ACTIONS_LIMIT: z.coerce.number().default(12),
  AUTONOMY_MAX_ACTIONS_PER_TICK: z.coerce.number().default(3),
  AUTONOMY_MAX_LOVABLE_BUILDS_PER_TICK: z.coerce.number().default(1),
  AUTONOMY_MAX_JOBS_PER_TICK: z.coerce.number().default(3),
  AUTONOMY_MAX_LOVABLE_JOBS_PER_TICK: z.coerce.number().default(1),
  AUTONOMY_MAX_FILMER_JOBS_PER_TICK: z.coerce.number().default(1),
  AUTONOMY_JOB_LOCK_MINUTES: z.coerce.number().default(30),
  AUTONOMY_DEAD_AFTER_ATTEMPTS: z.coerce.number().default(3),
  LOVABLE_BUILD_INTERVAL_HOURS: z.coerce.number().default(2),
  DATA_DIR: z.string().default('./data'),
  OPENAI_API_KEY: z.string().optional().default(''),
  OPENAI_MODEL: z.string().default('gpt-5.4'),
  YANDEX_MAPS_API_KEY: z.string().optional().default(''),
  YANDEX_MAPS_LANG: z.string().default('ru_RU'),
  YANDEX_MAPS_RESULTS: z.coerce.number().default(25),
  LEAD_SOURCE_PROVIDER: z.enum(['yandex', 'google', 'both']).default('yandex'),
  GOOGLE_MAPS_API_KEY: z.string().optional().default(''),
  GOOGLE_CSE_ID: z.string().optional().default(''),
  GOOGLE_MAPS_RESULTS: z.coerce.number().default(20),
  GOOGLE_DAILY_SEARCH_LIMIT: z.coerce.number().default(100),
  SCOUT_AREA_MODE: z.enum(['city', 'districts']).default('districts'),
  SCOUT_QUERY_COOLDOWN_DAYS: z.coerce.number().default(7),
  SCOUT_GOOGLE_PAGES: z.coerce.number().default(2),
  SCOUT_YANDEX_PAGES: z.coerce.number().default(2),
  SCOUT_DISTRICTS_JSON: z.string().optional().default(''),
  SCOUT_CITIES: z.string().default('Москва,Казань,Екатеринбург,Краснодар'),
  SCOUT_NICHES: z.string().default('кровельщики,салон красоты,кондиционеры'),
  MIN_YEARS_ON_MAP: z.coerce.number().default(5),
  MAX_REVIEWS: z.coerce.number().default(50),
  MIN_RATING: z.coerce.number().default(4.4),
  DAILY_MOCKUP_LIMIT: z.coerce.number().default(10),
  DAILY_SEND_LIMIT: z.coerce.number().default(25),
  OUTBOUND_WORKING_HOURS_START: z.coerce.number().default(9),
  OUTBOUND_WORKING_HOURS_END: z.coerce.number().default(18),
  OUTBOUND_TIMEZONE: z.string().default('Europe/Moscow'),
  FILMER_ENABLED: boolFromEnv.default('true'),
  FILMER_SCREENSHOT_COUNT: z.coerce.number().default(5),
  FILMER_VIDEO_SECONDS: z.coerce.number().default(10),
  DEAL_APPROVAL_RUB: z.coerce.number().default(300000),
  MIN_REPLY_RATE: z.coerce.number().default(12),
  A1_API_URL: z.string().default('http://localhost:4000'),
  A1_API_KEY: z.string().optional().default(''),
  A1_COMPANY_ID: z.string().optional().default(''),
  A1_MCP_URL: z.string().optional().default(''),
  A1_MCP_API_KEY: z.string().optional().default(''),
  A1_MCP_AUTH_HEADER: z.string().default('x-a1-mcp-key'),
  A1_MCP_ROLE: z.string().default('operator'),
  A1_MCP_ENVIRONMENT: z.string().default('production'),
  A1_MCP_ACTOR_ID: z.string().default('web-studio-orchestrator'),
  A1_AGENT_ENVIRONMENT: z.string().default('local'),
  A1_CRM_LEADS_WORKFLOW_ID: z.string().optional().default(''),
  A1_OUT_DELIVERY_WORKFLOW_ID: z.string().optional().default(''),
  A1_VOICE_CALL_WORKFLOW_ID: z.string().optional().default(''),
  A1_ISSUE_INVOICE_WORKFLOW_ID: z.string().optional().default(''),
  A1_YOOKASSA_WORKFLOW_ID: z.string().optional().default(''),
  A1_YANDEX_SEARCH_TOOL: z.string().optional().default(''),
  A1_YANDEX_SEARCH_WORKFLOW_ID: z.string().optional().default(''),
  A1_WEBHOOK_SECRET: z.string().optional().default(''),
  LOVABLE_MCP_URL: z.string().optional().default(''),
  LOVABLE_MCP_API_KEY: z.string().optional().default(''),
  LOVABLE_OFFICIAL_MCP_URL: z.string().default('https://mcp.lovable.dev'),
  LOVABLE_API_KEY: z.string().optional().default(''),
  LOVABLE_OAUTH_TOKEN_PATH: z.string().default('./data/lovable-oauth.json'),
  LOVABLE_WORKSPACE_ID: z.string().optional().default(''),
  LOVABLE_AUTO_DEPLOY: boolFromEnv.default('false'),
  LOVABLE_TOKEN_HEARTBEAT_ENABLED: boolFromEnv.default('true'),
  LOVABLE_TOKEN_HEARTBEAT_CRON: z.string().default('*/30 * * * *'),
  GITHUB_TOKEN: z.string().optional().default(''),
  GITHUB_OWNER: z.string().default('1Lab-vibe'),
  GITHUB_REPO_PREFIX: z.string().default('webstudio-'),
  GITHUB_PRIVATE: boolFromEnv.default('false'),
  GITHUB_PUBLISH_MODE: z.enum(['auto', 'api', 'ssh', 'off']).default('auto'),
  GITHUB_SSH_HOST: z.string().default('github.com'),
  TELEGRAM_BOT_TOKEN: z.string().optional().default(''),
  TELEGRAM_CHAT_ID: z.string().optional().default(''),
  TELEGRAM_ADMIN_USER_IDS: z.string().optional().default(''),
  TELEGRAM_BOT_USERNAME: z.string().optional().default(''),
  TELEGRAM_WEBHOOK_SECRET: z.string().optional().default(''),
  PUBLIC_BASE_URL: z.string().default('https://webstudio.1true.ru'),
  LEGAL_OPERATOR_NAME: z.string().default('ИП Трушков Иван Алексеевич'),
  LEGAL_OPERATOR_EMAIL: z.string().default('1lab@1true.ru'),
  LEGAL_OPERATOR_ADDRESS: z.string().optional().default(''),
  LEGAL_OPERATOR_INN: z.string().optional().default('500804863530'),
  LEGAL_OPERATOR_OGRN: z.string().optional().default(''),
  WEB_STUDIO_MCP_TOKEN: z.string().optional().default(''),
  WEB_AUTH_LOGIN: z.string().optional().default(''),
  WEB_AUTH_PASSWORD: z.string().optional().default(''),
  WEB_AUTH_SESSION_SECRET: z.string().optional().default(''),
  LOVABLE_EMAIL: z.string().optional().default(''),
  LOVABLE_PASSWORD: z.string().optional().default(''),
  LOVABLE_STORAGE_STATE: z.string().default('./data/lovable-storage-state.json'),
  LOVABLE_HEADLESS: boolFromEnv,
  LOVABLE_BROWSER_CHANNEL: z.string().optional().default(''),
  LOVABLE_USE_CHROME_PROFILE: boolFromEnv,
  LOVABLE_CHROME_USER_DATA_DIR: z.string().optional().default(''),
  LOVABLE_CHROME_PROFILE: z.string().default('Default'),
  LOVABLE_CDP_URL: z.string().default('http://127.0.0.1:9222'),
});

export const config = envSchema.parse(process.env);

export function csv(value) {
  return value
    .split(',')
    .map((item) => item.trim())
    .filter(Boolean);
}

export function hasSecret(value) {
  return Boolean(value && value.trim().length > 0);
}
